# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: LibreWolf.LibreWolf
PackageVersion: 124.0.1-1
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
Protocols:
  - http
  - https
FileExtensions:
  - htm
  - html
  - url
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
      MinimumVersion: 14.38.33135.0
Installers:
  - InstallerLocale: en-US
    Architecture: x64
    InstallerType: nullsoft
    Scope: machine
    InstallerUrl: https://gitlab.com/api/v4/projects/44042130/packages/generic/librewolf/124.0.1-1/librewolf-124.0.1-1-windows-x86_64-setup.exe
    InstallerSha256: c8a97dd57ac10928db8d5840358b4c8c4b51ca638348f1146e49a74782f042d5
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.6.0
